apiVersion: batch/v1
kind: Job
metadata:
  name: twozerofoureight-job
spec:
  template:
    spec:
      containers:
      - name: twozerofoureight-job
        image: yash5090/twozerofoureight:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
