apiVersion: v1
kind: Service
metadata:
  name: twozerofoureight-service
spec:
  selector:
    app: twozerofoureight
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
