apiVersion: apps/v1
kind: Deployment
metadata:
  name: twozerofoureight-deployment
spec:
  replicas: 3 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: twozerofoureight
  template:
    metadata:
      labels:
        app: twozerofoureight
    spec:
      containers:
        - name: twozerofoureight
          image: yash5090/twozerofoureight:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
